### ISSUE TITLE
Game Narrative 

### ISSUE THREAD

**Issue by tramstheman** [North-Vine-Engineering/Dungeon-Dweller-2#2]
Design a game narrative and story line as a driving force for the game.

**Comment by GEvanscsumb** [comment]
Created a general storyline. Going to connect it with events on a draft map to improve it.

**Comment by tramstheman** [comment]
Can you upload any docs you have for this into? We should make a docs folder that contains this information.

**Comment by GEvanscsumb** [comment]
Done. Comitted in my branch.

**Comment by tramstheman** [comment]
sweet! Make a pull request to master
