### ISSUE TITLE
Game Stops Working After Dialogue 

### ISSUE THREAD

**Issue by tramstheman** [North-Vine-Engineering/Dungeon-Dweller-2#25]
![image_uploaded_from_ios_1024](https://cloud.githubusercontent.com/assets/6572099/25211362/c70455a6-2539-11e7-85f6-cfb879d5059a.jpg)

**Comment by GEvanscsumb** [comment]
what happens after you hit ok?

**Comment by tramstheman** [comment]
I am going to try running locally and see if I can reproduce it

**Comment by tramstheman** [comment]
@akatrent

**Comment by GEvanscsumb** [comment]
problem is with rail function. debugging now

**Comment by tramstheman** [comment]
sweet, make a PR and we will review it and after we accept it we will close this out.

**Comment by GEvanscsumb** [comment]
fixed in #26
