### ISSUE TITLE
Relative Paths

### ISSUE THREAD

**Issue by tramstheman** [North-Vine-Engineering/Dungeon-Dweller-2#5]
Figure out relative paths so we can dynamically load assets from the project workspace.

**Comment by tramstheman** [comment]
I found a way around this in JES. Unfortunately there is no way to code in relative paths, however we can use paths relative to the "getMediaPath" which we can allow the user to set upon game initialization. The caviat is that we have to make sure they actually select the media folder and if they don't we need to throw some sort of exception immediately.

**Comment by akatrent** [comment]
Yes, I agree there is no way to do relative paths in JES as it pulls the working directory from where JES is executing. I was working with getMediaPath earlier this week. I'll post my code for review
