### ISSUE TITLE
Ad Hoc Testing

### ISSUE THREAD

**Issue by tramstheman** [North-Vine-Engineering/Dungeon-Dweller-2#8]
This will be the final QA Process before Release

**Comment by tramstheman** [comment]
How are we on adhoc testing?

**Comment by GEvanscsumb** [comment]
In the multiple runs I've done, as far as room functionality and user input goes, nothing is wrong/will break the game. I would say main concern would just be narrative accuracy/ grammar because I made some changes with the script when I separated it into smaller files.

**Comment by tramstheman** [comment]
have you ran all the files through a spell checker? 
also, I reviewed all the changes in [#22](https://github.com/North-Vine-Engineering/Dungeon-Dweller-2/pull/22) and all the spelling/grammar looked fine

**Comment by GEvanscsumb** [comment]
ran through all of them in office. everything checks out there.
